### ISSUE TITLE
Crash in log_muncher.rb SyntaxError

### ISSUE THREAD

**Issue by MikolajKakol** [mttkay/replicant#31]
I don't have any experience with ruby, but I think is a bug. Stacktrace below. 

```
$ replicant 
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': /var/lib/gems/1.9.1/gems/replicant-adb-1.0.1/lib/replicant/log_muncher.rb:39: syntax error, unexpected keyword_do_block, expecting keyword_end (SyntaxError)
    transform_line(line).each do |seg|
                            ^
/var/lib/gems/1.9.1/gems/replicant-adb-1.0.1/lib/replicant/log_muncher.rb:83: syntax error, unexpected keyword_end, expecting $end
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /var/lib/gems/1.9.1/gems/replicant-adb-1.0.1/lib/replicant.rb:8:in `<top (required)>'
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /var/lib/gems/1.9.1/gems/replicant-adb-1.0.1/bin/replicant:3:in `<top (required)>'
    from /usr/local/bin/replicant:23:in `load'
    from /usr/local/bin/replicant:23:in `<main>'
```

I'm not sure what kind of information about my system you might need, I'm using Mint 17 Cinamon 64-bit

```
$ ruby -v
ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]
$ uname -a
Linux GT680 3.13.0-24-generic #47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by yuanzhanxue** [comment]
I meet the same issue.
